[package]
name = "hum"
version = "0.1.0"
authors = ["Brian Bassett <bbassett1276@gmail.com>"]
edition = "2024"
description = "A configurable user manager for homelab use."
readme = "README.md"
repository = "https://github.com/bribass/hum"
license = "Apache-2.0"

[dependencies]
toml = "0.9.2"
